### ISSUE TITLE
Allow MonadRandom interface for MWC-random

### ISSUE THREAD

**Issue by ghost** [byorgey/MonadRandom#26]
We'd like to be able to define a `MonadRandom` instance for a `newtype`'d `ST`, using the same `unsafePerformIO` `IORef` trick as the `IO` instance, but with `MWC-random`'s `Gen` rather than the `System.Random` `Gen`. 
Fundamentally, the problem is that `random` et al require 
This is sad because the interface should be exactly the same.
One solution is to eliminate the `Random a` requirement and fix a return type (`Word32`, `Int`,`Double`, etc), since all random generators fundamentally operate on these primitive types.  Another solution is to make a multiparam version of `MonadRandom` parameterizing the generator type and/or return type.

I'd pick the first solution, but I'd like to know if anyone has a use-case for baking different randomness mechanisms into the `Random` typeclass, rather than just post applying an `f :: Int -> A` or somesuch

**Comment by byorgey** [comment]
Hi @dogirardo , sorry for not responding before now.  I'm currently doing some major updates to `MonadRandom`, and would love to figure out a solution to this issue.  For starters, though, I am not sure I completely understand what the problem is.  You say "Fundamentally, the problem is that random et al require" but it seems like you did not complete that sentence.  Could you please clarify?  Thanks!

**Comment by jp-beaumont** [comment]
To implement `getRandom :: Random a => m a` one needs access to a type that implements `RandomGen` to use when calling the methods from `Random`. `mwc-random` doesn't [and can't] implement `RandomGen`. One proposed solution is to modify `MonadRandom` so that `getRandom :: m Word32`. The second proposal generalizes this to

    class MonadRandom m a where
        getRandom :: m a

Neither of these is as flexible or convenient as the current setup in cases where a `MonadGen` instance exists. A third alternative which is a strict generalization of the current `MonadRandom` would be

    class MonadRandom m where
        type Random m a :: Constraint
        getRandom :: Random m a => m a

This would allow each `MonadRandom` instance to specify the subset of types it is capable of generating. I would favour this third solution but it requires the ConstraintKinds and TypeFamilies extensions and I don't know if there is any policy on using/avoiding certain extensions in `MonadRandom`.

**Comment by Shimuuar** [comment]
Main difference between PRNGs from `random` and `mwc-random` is their state. State of PRNG from `random`  is pure value and could be threaded in state monad. And state of mwc-random is mutable buffer. It's large: 258 Word32 so for performance reasons it's modified in place. 

Therefore different `RandT`s are needed for different generators. `StateT Gen m` for ones with pure state and `MonadIO/St m ⇒ ReaderT Gen m` for ones with mutable state.

**Comment by ygale** [comment]
How about something like this:

    newtype PrimMonad m => RandMwcT m a = RandMwcT (ReaderT (Gen (PrimState m)) m a)
      deriving ( Monad, {- lots of stuff -} )

    class Monad m => RandomM m a where
      getRandomM :: m a
      -- etc., like current MonadRandom but without the Random constraints

    instance (Monad m, RandomGen g, Random a) => RandomM (RandT g m) a where
      getRandomM = getRandom
      -- etc.

    instance (PrimMonad m, Variate a) => RandomM (RandMwcT m) a where
      getRandom = RandMwcT $ asks uniform
      getRandomR = RandMwcT $ asks uniformR
      -- etc.

This is a non-breaking change. We are only adding a new type and and a class, not touching the current `RandT` and `MonadRandom` class.

Note that `RandomM` is *not* an instance of `Monad`, unlike `MonadRandom`. You use it as a constraint with two type parameters. Types with this constraint are then compatible with both `System.Random` and [mwc-random](http://hackage.haskell.org/package/mwc-random) if your monad is an instance of `PrimMonad` and your value is an instance of both `Random` and `Variate`.

**Comment by dogirardo** [comment]
Ahh sorry for the omission/typo, but @jp-beaumont sums up what I was going to say

**Comment by idontgetoutmuch** [comment]
You can already do this in `random-fu`. NB I am absolutely not saying it is better but just trying to inform debate to reach a better place.

```
{-# OPTIONS_GHC -Wall #-}

import Data.Random
import Control.Monad.Reader
import Data.Random.Source.MWC
import qualified Control.Monad.Random as M
import qualified Data.Vector as V

die :: (M.RandomGen g) => M.Rand g Int
die = M.getRandomR (1,6)

dice :: (M.RandomGen g) => Int -> M.Rand g [Int]
dice n = sequence (replicate n die)

die' :: MonadRandom m => m Int
die' = sample (uniform 1 6)

dice' :: MonadRandom m => Int -> m [Int]
dice' n = sequence (replicate n die')

main :: IO ()
main = do
  seed <- initialize (V.fromList [2])
  values' <- runReaderT (dice' 10000) seed
  putStrLn (show $ sum values')
  values <- M.evalRandIO (dice 10000)
  putStrLn (show $ sum values)
```

**Comment by lehins** [comment]
I think this issue can be closed now, since `random` has full support for stateful and pure generators alike, including `mwc-random`. More info can be found in this talk: https://www.youtube.com/watch?v=GGbPqSM1ADw

Moreover #47 makes it possible to use `RandT` with the same `StatefulGen` interface.

**Comment by byorgey** [comment]
Thanks!  I will try to take a look at #47 soon.
