### ISSUE TITLE
MonadIO Instance

### ISSUE THREAD

**Issue by jbaum98** [byorgey/MonadRandom#40]
Is there a reason why we don't have an instance of `MonadRandom` for all `MonadIO` monads? Something like
```haskell
instance {-# OVERLAPS #-} (Monad m, MonadIO m) => MonadRandom m where
    getRandomR = liftIO . getRandomR
    getRandom = liftIO getRandom
    getRandomRs = liftIO . getRandomRs
    getRandoms = liftIO getRandoms
```

**Comment by byorgey** [comment]
Well, yes, the reason is the `{-# OVERLAPS #-}` thing.  This instance would overlap with *every* other instance of `MonadRandom`.  Note that this instance does *not* mean "every `MonadIO` is a `MonadRandom`"; it actually means "every type `m` is a `MonadRandom`, and by the way, it had better be a `Monad` and `MonadIO` too".

**Comment by jbaum98** [comment]
Is there a better way of running a MonadRandom computation given only the MonadIO constraint? Just using liftIO?

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by byorgey** [comment]
No, I think writing `liftIO . getRandomR` and so on is the correct approach.  Note you could make a `newtype` wrapper around your monad and make an instance of `MonadRandom` for it which implements the methods via `liftIO`.

**Comment by jbaum98** [comment]
Okay sounds good. Would another option be to remove the IO instance and just leave the MonadIO instance? IO is an instance of MonadIO right? Or is the problem not the overlap but the vagueness of the MonadIO instance because it's just an m on the right of the => ?

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jbaum98** [comment]
Another thought: when I have a function that only needs the `MonadRandom` constraint, it feels not-ideal to give the "dangerous" `MonadIO` constraint.

**Comment by byorgey** [comment]
`IO` is an instance of `MonadIO`, yes.  But if we added an `instance MonadIO m => MonadRandom m`, the problem is not that it would overlap with the `IO` instance. The problem is that it would overlap with every `MonadRandom` instance, ever!  When Haskell looks for an instance for a certain type, it first just looks at the part to the right of the `=>` to see if it matches.  So if it is trying to find an instance for `MonadRandom Rand`, it sees that `Rand` matches the `m` (a variable matches anything), so it picks that instance.  It then deals with the part to the left of the `=>`, generating an additional constraint, in this case, `MonadIO Rand` (which is nonsense).

I'm not sure what you mean about giving a `MonadIO` constraint instead of a `MonadRandom` constraint.  I agree it is not ideal to give a `MonadIO` constraint if what you really need is a `MonadRandom` constraint.  But I don't understand what that has to do with anything.

**Comment by jbaum98** [comment]
Thanks for explaining that. I didn't understand how instances are resolved. 

You said the right approach is `liftIO . getRandomR`, but that requires a `MonadIO` constraint instead of a `MonadRandom` constraint. The best solution, at least in my case, was just to write that `MonadRandom` instance above for the specific type I was using, making use of the `MonadIO` instance of that type.
